language: python
python:
- '3.8'
before_install:
- echo "TRAVIS_PULL_REQUEST is '${TRAVIS_PULL_REQUEST}'"
install:
- pip install Sphinx
- pip install recommonmark
script:
- ./tests.sh
- sphinx-build -n -b html -d build/doctrees source/ build/html
- make build/html/_static/css/app.css
- make build/html/_static/app.js
