version: '3.7'
services:
  sphinx_autobuild:
    container_name: sphinx_autobuild
    build:
      context: .
      dockerfile: ./Autobuild-Dockerfile
    volumes:
      - ./:/build/
    ports:
      - 8000:8000
