apiVersion: batch/v1
kind: Job
metadata:
  name: app-job
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: es-populator
          image: populatorImage
          env:
            - name: POPULATOR_ES_HOST
              value: elasticsearch
