---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: docs-ukfast-co-uk
spec:
  dnsNames:
  - 'docs.ukfast.co.uk'
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod-safedns
  secretName: docs-ukfast-co-uk-tls
