apiVersion: batch/v1
kind: Job
metadata:
  name: app-job
spec:
  ttlSecondsAfterFinished: 180
  template:
    spec:
      containers:
        - name: es-populator
          image: populatorImage
          imagePullPolicy: Always
          env:
            - name: POPULATOR_ES_HOST
              value: PLACEHOLDER
